routes/web.php
<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\PlayersController;
use App\Http\Controllers\MailController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/test-mail',[MailController::class,'testMail']);
Route::prefix('blog')->name('blog.')->group(function () {
    Route::get('/', [BlogController::class,'index'])->name('index');
    // them cau thu
    Route::get('/add', [BlogController::class,'add'])->name('add');
    Route::post('/add', [BlogController::class,'postAdd']);
    // sua cau thu
    Route::get('/edit/{id}', [BlogController::class,'edit'])->name('edit');
    Route::post('/edit/{id}', [BlogController::class,'postEdit'])->name('post-edit');

    Route::get('/delete/{id}',[BlogController::class,'delete'])->name('delete');
    // demo validate request
    Route::get('/demo',[BlogController::class,'demo'])->name('demo');
    Route::post('/demo',[BlogController::class,'postDemo'])->name('post-demo');
    // tao route de gui mail

});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// tao route moi
Route::prefix('players')->name('players.')->group(function(){
    Route::get('/',[PlayersController::class,'index'])->name('index');
    Route::get('/add',[PlayersController::class,'add'])->name('add');
    Route::post('/add',[PlayersController::class,'postAdd'])->name('post-add');
});

app/Models/Players.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Players extends Model
{
    use HasFactory;
    protected $table = 'players';
    protected $fillable = ['name','age','national','position','salary','avatar'];
    public $timestamps = false;
}

app/Http/Controllers/PlayersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\DemoRequest;
use Illuminate\Http\Request;

use App\Http\Requests\PlayersRequest;

use DB;

class PlayersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title = "Danh sach cau thu";
        $players = DB::select('select * from `players`');
        return view('players.lists',compact('title','players'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function add()
    {
        // Hien thi bang them cau thu
        $title = "Them cau thu";
        return view('players.add',compact('title'));
    }

    public function postAdd(DemoRequest $request)
    {
        // Xu ly them cau thu

        $dataRequest = $request->all();
        
       
    }



    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/players/add.blade.php
@extends('layout')
@section('title')
    {{$title}}
@endsection
@section('noidung')
    <h1>{{$title}}</h1>
    @if ($errors->any())
        <div class="alert alert-danger">
            <p>Them cau thu khong thanh cong</p>
        </div>
    @endif
    <form action="" method="POST" enctype="multipart/form-data">
        <div>
            <label for="">Name</label>
            <input type="text"  name="name" class="form-control" value="{{old('name')}}">
            @error('name')
                <span style="color: red;">{{$message}}</span>
            @enderror
            
        </div>
        <div>
            <label for="">Avatar</label>
            <input type="file"  name="avatar" class="form-control" >
            @error('avatar')
                <span style="color: red;">{{$message}}</span>
            @enderror
            
        </div>
        <div>
            <label for="">Age</label>
            <input type="text"  name="age" class="form-control" value="{{old('age')}}">
            @error('age')
            <span style="color: red;">{{$message}}</span>
            @enderror

        </div>
        <div>
            <label for="">National</label>
            <input type="text"  name="national" class="form-control" value="{{old('national')}}">
            @error('national')
            <span style="color: red;">{{$message}}</span>
            @enderror
        </div>
        <div>
            <label for="">Position</label>
            <input type="text"  name="position" class="form-control" value="{{old('position')}}">
            @error('position')
            <span style="color: red;">{{$message}}</span>
            @enderror
        </div>
        <div>
            <label for="">Salary</label>
            <input type="text"  name="salary" class="form-control" value="{{old('salary')}}">
            @error('name')
            <span style="color: red;">{{$message}}</span>
            @enderror
        </div>
        <br>
        <button type="submit" class="btn btn-success">Them moi</button>
        <a href="{{route('players.index')}}" type="button" class="btn btn-primary">Quay ve</a>   
        @csrf
-    </form>
    <br>
    
@endsection

resources/views/players/demo.blade.php
@extends('layout')
@section('title')
    {{$title}}
@endsection
@section('noidung')
    <h1>{{$title}}</h1>
    @if ($errors->any())
        <div class="alert alert-danger">
            <p>Them cau thu khong thanh cong</p>
        </div>
    @endif
    <form action="" method="POST">
        <div>
            <label for="">Name</label>
            <input type="text" value="{{old('name')}}" name="name" class="form-control" >
            @error('name')
                <span style="color:red;">{{$message}}</span>
            @enderror
        </div>
        <div>
            <label for="">Age</label>
            <input type="text" value="{{old('age')}}" name="age" class="form-control" >
            @error('age')
                <span style="color:red;">{{$message}}</span>
            @enderror

        </div>
        <div>
            <label for="">National</label>
            <input type="text" value="{{old('national')}}" name="national" class="form-control" >
            @error('national')
                <span style="color:red;">{{$message}}</span>
            @enderror
        </div>
        <div>
            <label for="">Position</label>
            <input type="text" value="{{old('position')}}" name="position" class="form-control" >
            @error('position')
                <span style="color:red;">{{$message}}</span>
            @enderror
        </div>
        <div>
            <label for="">Salary</label>
            <input type="text" value="{{old('salary')}}" name="salary" class="form-control" >
            @error('salary')
                <span style="color:red;">{{$message}}</span>
            @enderror
        </div>
        <br>
        <button type="submit" class="btn btn-success">Them moi</button>
        <a href="{{route('blog.index')}}" type="button" class="btn btn-primary">Quay ve</a>   
        @csrf
-    </form>
    <br>
    
@endsection

resources/views/players/edit.blade.php
@extends('layout')
@section('title')
    {{$title}}
@endsection
@section('noidung')
    <h1>{{$title}}</h1>
    <form action="" method="POST">
        <div>
            <label for="">Name</label>
            <input type="text" value="{{old('name') ?? $dataDetail[0]->name}}" name="name" class="form-control" value="1" placeholder="name">
            @error('name')
                <span style="color:red;">{{$message}}</span>
            @enderror
        </div>
        <div>
            <label for="">Age</label>
            <input type="text" value="{{old('age') ?? $dataDetail[0]->age}}" name="age" class="form-control" >
            @error('age')
                <span style="color:red;">{{$message}}</span>
            @enderror

        </div>
        <div>
            <label for="">National</label>
            <input type="text" value="{{old('national') ?? $dataDetail[0]->national}}" name="national" class="form-control" >
            @error('national')
                <span style="color:red;">{{$message}}</span>
            @enderror
        </div>
        <div>
            <label for="">Position</label>
            <input type="text" value="{{old('position') ?? $dataDetail[0]->position}}" name="position" class="form-control" >
            @error('position')
                <span style="color:red;">{{$message}}</span>
            @enderror
        </div>
        <div>
            <label for="">Salary</label>
            <input type="text" value="{{old('salary') ?? $dataDetail[0]->salary}}" name="salary" class="form-control" >
            @error('salary')
                <span style="color:red;">{{$message}}</span>
            @enderror
        </div>
        <br>
        <button type="submit" class="btn btn-success">Cap nhat</button>
        <a href="{{route('blog.index')}}" type="button" class="btn btn-primary">Quay ve</a>   
        @csrf
-    </form>
    <br>
    
@endsection

resources/views/players/lists.blade.php
@extends('layout')
@section('title')
    {{$title}}
@endsection
@section('noidung')
    <h1>{{$title}}</h1>
    <table class="table table-bodered">
        <thead class="bg-light">
           <tr>
            <th>name</th>
            <th>age</th>
            <th>national</th>
            <th>posittion</th>
            <th>salary</th>
            <td>Edit</td>
            <td>Delete</td>
           </tr>
        </thead>
        <tbody>
            @if (!empty($players))
                @foreach ($players as $player)
                <tr>
                    <td>{{$player->name}}</td>
                    <td>{{$player->age}}</td>
                    <td>{{$player->national}}</td>
                    <td>{{$player->position}}</td>
                    <td>{{$player->salary}}</td>
                    <td><a href="{{route('blog.edit',['id'=>$player->id])}}" class="btn btn-warning">Edit</a></td>                    
                    <td><a href="{{route('blog.delete',['id'=>$player->id])}}" class="btn btn-info">Delete</a></td>                    

                </tr>
                @endforeach
            @else
                <tr>
                    <td colspan="5">Khong co cau thu</td>
                </tr>
            @endif
        </tbody>
    </table>
    <a href="{{route('players.add')}}" type="button" class="btn btn-primary">Them cau thu</a>   
@endsection